name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Actions Environment (Ubuntu)
        run: |
          echo CI = $CI
          echo GITHUB_WORKFLOW = $GITHUB_WORKFLOW
          echo GITHUB_RUN_ID = $GITHUB_RUN_ID
          echo GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER
          echo GITHUB_JOB = $GITHUB_JOB
          echo GITHUB_ACTION = $GITHUB_ACTION
          echo GITHUB_ACTION_PATH = $GITHUB_ACTION_PATH
          echo GITHUB_ACTIONS = $GITHUB_ACTIONS
          echo GITHUB_ACTOR = $GITHUB_ACTOR
          echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE = $GITHUB_WORKSPACE
          echo GITHUB_SHA = $GITHUB_SHA
          echo GITHUB_REF = $GITHUB_REF
          echo GITHUB_HEAD_REF = $GITHUB_HEAD_REF
          echo GITHUB_BASE_REF = $GITHUB_BASE_REF
          echo GITHUB_SERVER_URL = $GITHUB_SERVER_URL
          echo GITHUB_API_URL = $GITHUB_API_URL
          echo GITHUB_GRAPHQL_URL = $GITHUB_GRAPHQL_URL
          echo RUNNER_NAME = $RUNNER_NAME
          echo RUNNER_OS = $RUNNER_OS
          echo RUNNER_TEMP = $RUNNER_TEMP
          echo RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE

      - name: GitHub Actions Context
        run: |
          echo github.action = ${{ github.action }}
          echo github.action_path = ${{ github.action_path }}
          echo github.actor = ${{ github.actor }}
          echo github.github.base_ref = ${{ github.base_ref }}
          #echo github.event = ${{ github.event }}
          echo github.event_name = ${{ github.event_name }}
          echo github.event_path = ${{ github.event_path }}
          echo github.head_ref = ${{ github.head_ref }}
          echo github.job = ${{ github.job }}
          echo github.ref = ${{ github.ref }}
          echo github.ref_name = ${{ github.ref_name }}
          echo github.repository = ${{ github.repository }}

  macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Actions Environment (Ubuntu)
        run: |
          echo CI = $CI
          echo GITHUB_WORKFLOW = $GITHUB_WORKFLOW
          echo GITHUB_RUN_ID = $GITHUB_RUN_ID
          echo GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER
          echo GITHUB_JOB = $GITHUB_JOB
          echo GITHUB_ACTION = $GITHUB_ACTION
          echo GITHUB_ACTION_PATH = $GITHUB_ACTION_PATH
          echo GITHUB_ACTIONS = $GITHUB_ACTIONS
          echo GITHUB_ACTOR = $GITHUB_ACTOR
          echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE = $GITHUB_WORKSPACE
          echo GITHUB_SHA = $GITHUB_SHA
          echo GITHUB_REF = $GITHUB_REF
          echo GITHUB_HEAD_REF = $GITHUB_HEAD_REF
          echo GITHUB_BASE_REF = $GITHUB_BASE_REF
          echo GITHUB_SERVER_URL = $GITHUB_SERVER_URL
          echo GITHUB_API_URL = $GITHUB_API_URL
          echo GITHUB_GRAPHQL_URL = $GITHUB_GRAPHQL_URL
          echo RUNNER_NAME = $RUNNER_NAME
          echo RUNNER_OS = $RUNNER_OS
          echo RUNNER_TEMP = $RUNNER_TEMP
          echo RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE

      - name: GitHub Actions Context
        run: |
          echo github.action = ${{ github.action }}
          echo github.action_path = ${{ github.action_path }}
          echo github.actor = ${{ github.actor }}
          echo github.github.base_ref = ${{ github.base_ref }}
          #echo github.event = ${{ github.event }}
          echo github.event_name = ${{ github.event_name }}
          echo github.event_path = ${{ github.event_path }}
          echo github.head_ref = ${{ github.head_ref }}
          echo github.job = ${{ github.job }}
          echo github.ref = ${{ github.ref }}
          echo github.ref_name = ${{ github.ref_name }}
          echo github.repository = ${{ github.repository }}

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Actions Environment (Ubuntu)
        run: |
          echo CI = ${{ env.CI }}
          echo GITHUB_WORKFLOW = ${{ env.GITHUB_WORKFLOW }}
          echo GITHUB_RUN_ID = ${{ env.GITHUB_RUN_ID }}
          echo GITHUB_RUN_NUMBER = ${{ env.GITHUB_RUN_NUMBER }}
          echo GITHUB_JOB = ${{ env.GITHUB_JOB }}
          echo GITHUB_ACTION = ${{ env.GITHUB_ACTION }}
          echo GITHUB_ACTION_PATH = ${{ env.GITHUB_ACTION_PATH }}
          echo GITHUB_ACTIONS = ${{ env.GITHUB_ACTIONS }}
          echo GITHUB_ACTOR = ${{ env.GITHUB_ACTOR }}
          echo GITHUB_REPOSITORY = ${{ env.GITHUB_REPOSITORY }}
          echo GITHUB_EVENT_NAME = ${{ env.GITHUB_EVENT_NAME }}
          echo GITHUB_EVENT_PATH = ${{ env.GITHUB_EVENT_PATH }}
          echo GITHUB_WORKSPACE = ${{ env.GITHUB_WORKSPACE }}
          echo GITHUB_SHA = ${{ env.GITHUB_SHA }}
          echo GITHUB_REF = ${{ env.GITHUB_REF }}
          echo GITHUB_HEAD_REF = ${{ env.GITHUB_HEAD_REF }}
          echo GITHUB_BASE_REF = ${{ env.GITHUB_BASE_REF }}
          echo GITHUB_SERVER_URL = ${{ env.GITHUB_SERVER_URL }}
          echo GITHUB_API_URL = ${{ env.GITHUB_API_URL }}
          echo GITHUB_GRAPHQL_URL = ${{ env.GITHUB_GRAPHQL_URL }}
          echo RUNNER_NAME = ${{ env.RUNNER_NAME }}
          echo RUNNER_OS = ${{ env.RUNNER_OS }}
          echo RUNNER_TEMP = ${{ env.RUNNER_TEMP }}
          echo RUNNER_TOOL_CACHE=${{ env.RUNNER_TOOL_CACHE }}

      - name: GitHub Actions Context
        run: |
          echo github.action = ${{ github.action }}
          echo github.action_path = ${{ github.action_path }}
          echo github.actor = ${{ github.actor }}
          echo github.github.base_ref = ${{ github.base_ref }}
          #echo github.event = ${{ github.event }}
          echo github.event_name = ${{ github.event_name }}
          echo github.event_path = ${{ github.event_path }}
          echo github.head_ref = ${{ github.head_ref }}
          echo github.job = ${{ github.job }}
          echo github.ref = ${{ github.ref }}
          echo github.ref_name = ${{ github.ref_name }}
          echo github.repository = ${{ github.repository }}
